# Generated by Django 6.0.2 on 2026-02-15 13:55

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('scan_date', models.DateTimeField(blank=True, null=True)),
                ('import_date', models.DateTimeField(auto_now_add=True)),
                ('scanner_version', models.CharField(blank=True, default='', max_length=100)),
                ('host_count', models.IntegerField(default=0)),
                ('critical_count', models.IntegerField(default=0)),
                ('high_count', models.IntegerField(default=0)),
                ('medium_count', models.IntegerField(default=0)),
                ('low_count', models.IntegerField(default=0)),
                ('info_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-scan_date', '-import_date'],
            },
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('oid', models.CharField(blank=True, default='', max_length=200)),
                ('cvss_score', models.FloatField(default=0.0)),
                ('severity', models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Info', 'Info')], default='Info', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('solution', models.TextField(blank=True, default='')),
                ('family', models.CharField(blank=True, default='', max_length=500)),
                ('cve_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list)),
                ('references', models.JSONField(blank=True, default=dict)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilities', to='scanner.scanreport')),
            ],
            options={
                'verbose_name_plural': 'vulnerabilities',
                'ordering': ['-cvss_score', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AffectedHost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip', models.GenericIPAddressField()),
                ('hostname', models.CharField(blank=True, default='', max_length=500)),
                ('port', models.CharField(blank=True, default='', max_length=50)),
                ('protocol', models.CharField(blank=True, default='tcp', max_length=20)),
                ('result_detail', models.TextField(blank=True, default='')),
                ('vulnerability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affected_hosts', to='scanner.vulnerability')),
            ],
            options={
                'ordering': ['ip', 'port'],
            },
        ),
    ]
