# Generated by Django 6.0.2 on 2026-02-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanreport',
            name='gvm_report_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
