# Generated by Django 6.0.2 on 2026-02-25 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0003_organizationprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatGPTSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(blank=True, default='', max_length=500, verbose_name='API Key')),
                ('model', models.CharField(default='gpt-4.1', max_length=50, verbose_name='Model')),
                ('max_tokens', models.IntegerField(default=400, verbose_name='Max Tokens')),
                ('temperature', models.FloatField(default=0.0, verbose_name='Temperature')),
            ],
            options={
                'verbose_name': 'ChatGPT Settings',
                'verbose_name_plural': 'ChatGPT Settings',
            },
        ),
    ]
