# Generated by Django 6.0.2 on 2026-02-25 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0005_ai_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgptsettings',
            name='prompt_prefix',
            field=models.CharField(blank=True, default='อธิบาย', max_length=500, verbose_name='Prompt Prefix'),
        ),
        migrations.AddField(
            model_name='chatgptsettings',
            name='prompt_suffix',
            field=models.CharField(blank=True, default='และวิธีแก้ไขแบบเป็นขั้นตอน', max_length=500, verbose_name='Prompt Suffix'),
        ),
    ]
